# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cc158d19d7dcb7f112ca60ac8a4cb1f4461ea154ec9666ef2614dbcf700e75c3d7ce3e7628900aa65b8822f6ac2099657194bc771b365c5e3ed40d948911d95

test:
  secret_key_base: e539c42acf21fb593515e8b31cd5d26ebfea1e57aab210f4a75a88124e00bc0e2aadcfd7517ef1681e463745fc00cc0da30bc4fe8e7c633ac25cc251132ef64c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
